<a href="https://colab.research.google.com/github/Mahesh6702/ARM-M-processor-F446RE-Drivers-Development/blob/main/Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing all required libraries

In [ ]:
import numpy as np
import pandas as pd 
from matplotlib import pyplot as plt
from google.colab import files
import io
plt.style.use('seaborn-talk')

data = files.upload()

Saving Increasing_load.csv to Increasing_load.csv


Data Reading


In [ ]:
data = pd.read_csv(io.StringIO(data['sensor_data_csv.csv'].decode('utf-8')))

In [ ]:
data.head

<bound method NDFrame.head of        Resistance      Force
0        128949.0  10.978021
1        116466.0  12.327600
2        103478.0  14.003543
3         91778.7  14.561722
4         85254.7  15.421612
...           ...        ...
11966    138053.0   7.065283
11967    137618.0   6.721038
11968    138071.0   6.390000
11969    137446.0   5.751951
11970    138407.0   5.338313

[11971 rows x 2 columns]>

Splitting data into input(x) and output(y)

In [ ]:
X = data.iloc[:,0:1].values
y = data.iloc[:,1].values

In [ ]:
X

array([[128949.],
       [116466.],
       [103478.],
       ...,
       [138071.],
       [137446.],
       [138407.]])

In [ ]:
y

array([10.97802073, 12.32760027, 14.00354318, ...,  6.38999976,
        5.75195067,  5.33831306])

Splittting the Dataset into Training and Test Dataset


In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state =0)

In [ ]:
X_train

array([[2683.8],
       [4414.9],
       [4646.9],
       ...,
       [2331. ],
       [2215.5],
       [6223.7]])

In [ ]:
y_train

array([225.6852482, 266.1650814, 226.3994794, ..., 296.4291256,
       229.783114 , 126.3454836])

Linear Regression

In [ ]:
from sklearn.linear_model import LinearRegression
LinReg = LinearRegression()
LinReg.fit(X_train, y_train) # used for fitting the best fit line

LinearRegression()

In [ ]:
y_predict_slr = LinReg.predict(X_test)

from sklearn import metrics
r_square = metrics.r2_score(y_test, y_predict_slr)
print('R-Square Error associated with Linear Regression:',r_square) # r2_score evaluates how best is the model [o,1]

R-Square Error associated with Linear Regression: 0.24950057165878525


Polynomial Regression

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
#from sklearn.linear_model import LinearRegression
polynom = PolynomialFeatures(degree = 2)
polynom = PolynomialFeatures(degree = 3)
X_polynom = polynom.fit_transform(X_train)

X_polynom

Fitting the Polynomial regression Model

In [ ]:
PolyReg = LinearRegression()
PolyReg.fit(X_polynom, y_train)

LinearRegression()

In [ ]:
y_predict_slr =PolyReg.fit(X_test)

from sklearn import metrics
r_square = metrics.r2_score(y_test, y_predict_slr)
print('R-Square Error associated with polyonomial Regression degree =2:',r_square) # r2_score evaluates how best is the model [o,1]

R-Square Error associated with polynomial Regression degree =2:  0.44568379325